# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 13:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WMMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_content', models.CharField(max_length=99999)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
