# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WMUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WMMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_content', models.CharField(max_length=99999)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='WMUser.WMUser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='WMUser.WMUser')),
            ],
        ),
    ]
