# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WMMessage', '0001_initial'),
        ('WMUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmmessage',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='WMUser.WMUser'),
        ),
        migrations.AddField(
            model_name='wmmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='WMUser.WMUser'),
        ),
    ]
